const fs = require('fs');

const filePath = 'c:\\Users\\manta\\OneDrive\\Desktop\\SVETAINĖ\\svetaine\\src\\data\\blog-posts.json';
let data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Define Expanded Content for Batch 2 (40-44)
const updates = {
  "energinis-naudingumas-a-b-skirtumai": {
    "excerpt": "A++ vs B klasė: Energijos krizės pamokos. Nuodugniai analizuojame šildymo sąnaudas, vėdinimo (rekuperacijos) svarbą ir ilgalaikę turto vertę.",
    "content": "<h2>Energinis naudingumas: Naujas NT rinkos standartas</h2><p>Niekada anksčiau energinio naudingumo sertifikatas nebuvo toks svarbus pirkėjui, kaip šiandien. Kylant energetinių išteklių kainoms, būsto „sandarumas“ tampa ne tik komforto, bet ir tiesioginiu finansinio saugumo garantu. Nuo 2021 m. visi naujai statomi namai Lietuvoje privalo atitikti **A++ klasę**, tačiau rinkoje dominuoja ir B klasės būstai. Kuo jie skiriasi finansiškai ir praktiškai?</p><h3>A++ Klasė: Beveik nulinis energijos poreikis</h3><p>A++ klasė – tai aukščiausias pasiekimas būsto energetikoje. Šio tipo namai veikia kaip „termosas“ – jie sulaiko šilumą viduje ir neleidžia jai pasišalinti per sienas ar langus. Pagrindiniai reikalavimai:</p><ul><li>**Privaloma rekuperacijos sistema**: Atgauna iki 85% šilumos iš šalinamo oro ir tiekia šviežią orą be vėdinimo nuostolių.</li><li>**Atsinaujinantys šaltiniai**: Šilumos siurbliai (oras-vanduo, geoterminis) arba saulės elektrinės integravimas.</li><li>**Storas šiltinimo sluoksnis**: Sienų ir stogo izoliacija yra dvigubai efektyvesnė nei senesnės statybos namuose.</li></ul><p>Šildymo sąskaitos tokiame name dažnai būna simbolinės (pvz., 30-50 Eur per mėnesį šaltuoju periodu), tačiau pradinė statybos ar pirkimo kaina yra aukštesnė.</p><h3>B Klasė: Protingas biudžeto pasirinkimas?</h3><p>B klasės būstai dažniau sutinkami mūriniuose ar karkasiniuose namuose, statytuose prieš 5-10 metų. Jie yra geri ir patikimi, tačiau reikalauja daugiau energijos palaikyti šilumai.</p><ul><li>**Vėdinimas**: Dažniausiai natūralus (per langus ar ventiliacijos angas), kas reiškia didesnius šilumos nuostolius žiemą.</li><li>**Sąnaudos**: Šildymui išleidžiama 40-50% daugiau, nei A++ name, o vasarą gali prireikti kondicionavimo dėl prastesnės šilumos izoliacijos.</li></ul><h3>Investicinis atsiperkamumas: Ką rinktis?</h3><p>Jei planuojate gyventi name ilgiau nei 7 metus, investicija į A++ atsiperka su kaupu per sąskaitas ir didesnį būsto likvidumą ateityje. B klasė tinka tiems, kurie ieško patrauklesnės pradinės kainos ir planuoja būstą kaip laikiną etapą. <a href=\"/konsultacija\">Konsultacijos metu</a> parodysiu konkrečių objektų sąskaitas realiems skaičiavimams.</p>",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop"
  },
  "busto-paskolos-gavimas-atmintine": {
    "excerpt": "Atsakingas skolinimasis: 5 žingsniai išsamioje atmintinėje, kurie padidins jūsų šansus gauti geresnes banko maržas šių dienų ekonomikoje.",
    "content": "<h2>Kredito istorija: Svarbiausias banko filtras</h2><p>Būsto paskola yra daugiamečiai įsipareigojimai, todėl bankai pirkėją vertina per itin griežtą filtrą. Daugelis jaunų šeimų susiduria su netikėtais neigiamais atsakymais ne dėl pajamų trūkumo, o dėl netvarkingos finansinės higienos. Kaip paruošti savo profilį bankui?</p><h3>1. 40% Taisyklė (DSTI) ir Išlaidų analizė</h3><p>Lietuvos bankas numato, kad jūsų visų paskolų, lizingų ir kitų įsipareigojimų mėnesio įmoka negali viršyti **40% šeimos tvarių pajamų**. Bankas tikrins jūsų sąskaitos išrašus už paskutinius 6 mėnesius. Jei ten matysis azartiniai lošimai, greitieji kreditai ar nepaaiškinamas pinigų švaistymas – kredito reitingas kris akimirksniu.</p><h3>2. Stabilumas ir Nepertraukiamas Stažas</h3><p>Bankai reikalauja bent 6 mėnesių nepertraukiamo darbo stažo esamoje darbovietėje (pasibaigus bandomajam laikotarpiui). Jei dirbate pagal individualią veiklą – vertinamas bent 2 metų stabilus pelnas. Labai svarbu nekisti darbovietės prieš pat kreipiantis dėl kredito.</p><h3>3. Kitos Kreditinės Kortelės: Uždarykite jas</h3><p>Kreditinė kortelė su 2000 Eur limitu, net jei ji nenaudojama ir dulka stalčiuje, banko akyse skaičiuojama kaip jūsų įsipareigojimas. Prieš kreipiantis į banką, rekomenduojama uždaryti visas nebūtinas kredito linijas.</p><h3>4. Pradinis Įnašas: Kaip pasiekti geriausią maržą?</h3><p>Standartinis pradinis įnašas yra 15%. Sukaupę didesnį įnašą (pvz., 20-25%), parodote bankui savo discipliną ir galite drąsiai **derybose Spausti** banko maržą žemyn bent 0.2-0.3%. Sukurkite idealų vaizdą bankams. <a href=\"/konsultacija\">Gaukite nemokamą įvertinimą</a> prieš teikiant paraiškas.</p>",
    "image": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1200&auto=format&fit=crop"
  },
  "statybu-brokas-nauja-statyba": {
    "excerpt": "Nuo kreivų sienų iki pelėsio: Punktų sąrašas, kurį privalote patikrinti patys prieš pasirašant perdavimo aktą naujame name.",
    "content": "<h2>Naujos statybos spąstai: Nauja nereiškia tobula</h2><p>Pirkdami naujos statybos būstą su daline apdaila, pirkėjai dažnai būna sužavėti „naujumo“ kvapo ir estetiško fasado. Tačiau po gipso kartonu ar tinku gali slypėti statybų brokų sąrašas, kurį ištaisyti po garantinio laiko bus itin brangu.</p><h3>Ką būtina patikrinti per pirminę apžiūrą?</h3><ul><li>**Sienų ir grindų lygumas**: Kreivos grindys padidins išlaidas klijuojant plyteles ar dėdami parketą. Naudokite gulsčiuką arba lazerinį matuoklį.</li><li>**Elektros įvadai ir fiksacija**: Ar rozečių skaičius atitinka projektą, ar laidai nėra pažeisti gręžiant skyles. Patikrinkite visas jungtis.</li><li>**Vandentiekis ir kanalizacija**: Ar nėra drėgmės dėmių prie mazgų, ar kanalizacijos nuolydis teisingas. Vandens slėgis čiaupo mazguose.</li><li>**Pelėsis ir mikroklimatas**: Kampai turi būti absoliučiai sausi. Pelėsis naujame name – tragedija, reiškianti blogą ventiliacijos projektavimą arba pastato džiovinimo klaidą.</li></ul><h3>Techninio prižiūrėtojo galia</h3><p>Rekomenduoju į apžiūrą atsivesti nepriklausomą techninį atstovą (ekspertą). Jo paslauga kainuoja apie 100-200 Eur, tačiau jis pastebi kreives, langų sandarumo trūkumus naudojant termovizorių. Visa tai statytojas privalo sutaisyti savo lėšomis iki sandorio sudarymo. <a href=\"/konsultacija\">Nukreipsiu jus pas patikimus ekspertus</a> ramybei pasiekti.</p>",
    "image": "https://images.unsplash.com/photo-1503387762-592beb58ef23?q=80&w=1200&auto=format&fit=crop"
  },
  "investavimas-i-nt-nuomai": {
    "excerpt": "ROI skaičiavimai: Ilgalaikė vs Trumpalaikė nuoma. Kuri strategija pelningesnė šių dienų Kauno ir didmiesčių rinkoje.",
    "content": "<h2>Pasyvios pajamos iš NT: Realūs skaičiai ir mitai</h2><p>Investavimas į nekilnojamąjį turtą nuomai išlieka viena populiariausių ir saugiausių turto saugojimo formų. Tačiau norint pasiekti gerą investicijų grąžą (ROI), reikia pasirinkti teisingą strategiją, kuri atitiktų jūsų laisvo laiko resursus ir biudžetą.</p><h3>Ilgalaikė nuoma: Stabilumas ir Mažos sąnaudos</h3><p>Tai klasikinis modelis, kai butas išnuomojamas vieneriems ar daugiau metų. Grąža paprastai svyruoja tarp **4-6% per metus**.</p><ul><li>**Privalumai**: Mažiau laiko sąnaudų, pastovios pajamos, nuomininkas pats dengia komunalinius mokesčius.</li><li>**Rizika**: Deprezijuojančios kainos sutartyje dėl infliacijos, nusidėvėjimas ir teisiniai iššūkiai krapštant nemokius gyventojus.</li></ul><h3>Trumpalaikė nuoma (Airbnb / Booking)</h3><p>Gali generuoti 8-12% grąžą. Tačiau tai ne pasyvios pajamos – tai realus operatyvinis verslas.</p><ul><li>**Privalumai**: Didesnės pajamos už parą, lankstumas (galite naudoti būstą patys).</li><li>**Rizika**: Valymas, bendravimas su svečiais, kaimynų skundai daugiabučiuose ir didelės komisinės išlaidos platformoms.</li></ul><h3>Kaip teisingai apskaičiuoti ROI?</h3><p>Grynoji grąža (Net ROI) skaičiuojama atskaičius GPM mokestį (15%), bendrijos kaupiamuosius mokesčius, draudimą ir **amortizacijos rezervą** (baldų nusidėvėjimui). Skaičiuodami tik nuomos pajamas, darote klaidą. <a href=\"/konsultacija\">Užsisakykite tikslią skaičiuoklę</a> prieš pirkdami investicinį turtą.</p>",
    "category": "Rinkos Analizė",
    "author": "Mantas Katkevičius",
    "image": "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop"
  },
  "pakuoti-busta-pardavimui": {
    "excerpt": "Pakuotė parduoda prekę: Detalūs žingsniai, kaip pakelti būsto vertę už minimumą ir sukelti derybinį pranašumą.",
    "content": "<h2>Home Staging: Pirmasis įspūdis parduoda</h2><p>Pirkėjai nusprendžia, ar būstas jiems patinka, per pirmas 10 sekundžių nuo įėjimo pro duris. Prastas kvapas, tamsus prieškambaris ar per didelis kiekis asmeninių nuotraukų ant sienų blokuoja pirkėjo galimybę įsivaizduoti save tame būste.</p><h3>Greitas atnaujinimas su minimualiu biudžetu (iki 500 €):</h3><ul><li>**Baltų sienų magija**: Perdažykite nusidėvėjusias vietas šviesia, neutralia spalva. Tai sukuria švaros ir erdvės pojūtį akimirksniu.</li><li>**Apšvietimas**: Įsukite galingesnes lemputes su **šilta balta šviesa**. Ryškios patalpos vizualiai atrodo 10% didesnės.</li><li>**Asmeninių daiktų paslėpimas**: Vonios spintelės turi būti tuščios (jokių dantų šepetėlių), prieškambaris be 10 porų batų. Pirkėjas perka erdvę, o ne svetimo žmogaus kasdienybę.</li><li>**Kavos ar cinamono kvapas**: Tai senas, bet veikiantis gudrybės metodas. Malonūs kvapai sukelia jaukumo jausmą.</li></ul><p>Taisydami šias smulkmenas, jūs panaikinate derybinius pirkėjo argumentus. <a href=\"/konsultacija\">Parodykite man savo būstą</a> prieš fotosesiją, ir nurodysiu ką tiksliai patvartyti optimaliam vaizdui.</p>",
    "category": "Patarimai",
    "author": "Mantas Katkevičius",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop"
  }
};

// Update data
data = data.map(item => {
  if (updates[item.id]) {
    return { ...item, ...updates[item.id] };
  }
  return item;
});

fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
console.log("Batch 2 Expanded Successfully!");
